; PlatformIO Project Configuration File
;
; Using separate environments for transmitter and receiver and a dedicated PWM test build.

[env:robot]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino

lib_deps =
    mikem/RadioHead@^1.120
    lib/tagtronics
    lowpowerlab/RFM69
	arriflex/Adafruit Feather OLED@^1
	adafruit/Adafruit GFX Library@^1.12.6
	adafruit/Adafruit SSD1306@^2.5.16
	adafruit/Adafruit SH110X@^2.1.14

build_src_filter =
    +<robot/Robot.cpp>
    -<controller/>

[env:pwm_test]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino

lib_deps =
    mikem/RadioHead@^1.120
    lib/tagtronics
    lowpowerlab/RFM69
    sensirion/Sensirion I2C SEN66@^1.2.0

build_src_filter =
    +<robot/PWM_test.cpp>

build_flags =
    -D PWM_TEST_BUILD
