; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Using separate environments for transmitter and receiver to manage different source files and dependencies
; worth considering using a shared lib folder for common libraries.

[env:controller]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino

lib_deps =
    mikem/RadioHead@^1.120
    lib/tagtronics
    lowpowerlab/RFM69


build_src_filter =
    +<controller/>
    -<robot/>


[env:robot]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino

lib_deps =
    mikem/RadioHead@^1.120
    lib/tagtronics
    lowpowerlab/RFM69   
    
build_src_filter =
    +<robot/>
    -<controller/>

